spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/game-service
    username: rajp
    password: rajp

  sql:
    init:
      mode: never

  application:
    name: reactive-game-service

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8086/eureka