name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Maven package (skip tests)
        run: mvn clean package -DskipTests

      - name: Run JUnit tests
        run: mvn test

      - name: Build and start services with Docker Compose
        run: docker compose up --build -d
